wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1671625439.920261
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
